[project]
name = "staffsec-desktop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "click>=8.3.1",
    "robyn>=0.78.0",
]
